name: Release

on:
  workflow_dispatch:
    inputs:
      description: "Version to release"
      required: true

jobs:
  release:
    name: Create image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v1

      - name: Docker Buildx Run
        run: |
          docker buildx build \
            --push \
              --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
              --tag krystex/pingbot:${{ github.event.inputs.version }}
              --tag krystex/pingbot:latest \
              .
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Version ${{ github.event.inputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RUNNER_TOKEN }}
